/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lib_TinyEncryption */

#ifndef _Included_lib_TinyEncryption
#define _Included_lib_TinyEncryption
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lib_TinyEncryption
 * Method:    encrypt
 * Signature: ([B[J)V
 */
JNIEXPORT void JNICALL Java_lib_TinyEncryption_encrypt
  (JNIEnv *, jclass, jbyteArray, jlongArray);

/*
 * Class:     lib_TinyEncryption
 * Method:    decrypt
 * Signature: ([B[J)V
 */
JNIEXPORT void JNICALL Java_lib_TinyEncryption_decrypt
  (JNIEnv *, jclass, jbyteArray, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
