/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lib_NativeInsertionSort */

#ifndef _Included_lib_NativeInsertionSort
#define _Included_lib_NativeInsertionSort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lib_NativeInsertionSort
 * Method:    sort
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_lib_NativeInsertionSort_sort
  (JNIEnv *, jclass, jintArray);

#ifdef __cplusplus
}
#endif
#endif
